import { createContext, createElement, useContext, useEffect, useMemo, useState } from "react";
import { getStoredSchoolSection, type SchoolSection } from "@/lib/schoolSystem";

export type Language = "en" | "fr";

const frenchTranslations: Record<string, string> = {
    "Dashboard": "Tableau de bord",
    "Overview Dashboard": "Vue d’ensemble",
    "Students": "Élèves",
    "Total Students": "Nombre total d’élèves",
    "Active students": "Élèves actifs",
    "Teachers": "Enseignants",
    "Classes & Subjects": "Classes et matières",
    "Mark Entry": "Saisie des notes",
    "Student Attendance": "Présence des élèves",
    "Teacher Timetable": "Emploi du temps des enseignants",
    "Teacher Attendance": "Présence des enseignants",
    "Report Cards": "Bulletins scolaires",
    "Bulk Report Cards": "Bulletins en masse",
    "Class Lists": "Listes de classe",
    "Promotion": "Promotion",
    "Fees & Finance": "Frais et finances",
    "Teacher Salaries": "Salaires des enseignants",
    "Timetable": "Emploi du temps",
    "School Settings": "Paramètres de l’école",
    "School Portal": "Portail scolaire",
    "SCHOOL PORTAL": "PORTAIL SCOLAIRE",
    "Sign out": "Déconnexion",
    "Live": "En direct",
    "Welcome back": "Bon retour",
    "Here's what's happening across BCHS DOUALA today.": "Voici les actualités de BCHS DOUALA aujourd’hui.",
    "Here's what's happening across the school portal today.": "Voici les actualités du portail scolaire aujourd’hui.",
    "Fees Collected": "Frais collectés",
    "Pass Rate": "Taux de réussite",
    "Average / 20": "Moyenne / 20",
    "Class Averages": "Moyennes des classes",
    "Subject Averages": "Moyennes des matières",
    "Excellence Board": "Tableau d’excellence",
    "Top performing students": "Meilleurs élèves",
    "Sequence Performance Trend": "Évolution des résultats par séquence",
    "AI Insight": "Analyse par IA",
    "No data available": "Aucune donnée disponible",
    "No class data available": "Aucune donnée de classe disponible",
    "No subject data available": "Aucune donnée de matière disponible",
    "No sequence data available": "Aucune donnée de séquence disponible",
    "Updating dashboard summary…": "Mise à jour du tableau de bord…",
    "Dashboard summary unavailable": "Résumé du tableau de bord indisponible",
    "Dashboard data could not be loaded.": "Impossible de charger les données du tableau de bord.",
    "Retry": "Réessayer",
    "Best": "Meilleur",
    "Based on": "Basé sur",
    "students": "élèves",
    "classes": "classes",
    "shown": "affichées",
    "Subjects": "Matières",
    "Classes": "Classes",
    "Average": "Moyenne",
    "Search": "Rechercher",
    "Add": "Ajouter",
    "Edit": "Modifier",
    "Delete": "Supprimer",
    "Save": "Enregistrer",
    "Cancel": "Annuler",
    "Close": "Fermer",
    "Submit": "Valider",
    "Loading...": "Chargement...",
    "Loading…": "Chargement…",
    "Select": "Sélectionner",
    "Select class": "Sélectionner une classe",
    "Select a class": "Sélectionner une classe",
    "Name": "Nom",
    "Full Name": "Nom complet",
    "Gender": "Sexe",
    "Male": "Masculin",
    "Female": "Féminin",
    "Date": "Date",
    "Status": "Statut",
    "Present": "Présent",
    "Absent": "Absent",
    "Late": "En retard",
    "Excused": "Excusé",
    "Term": "Trimestre",
    "First Term": "Premier trimestre",
    "Second Term": "Deuxième trimestre",
    "Third Term": "Troisième trimestre",
    "Academic Year": "Année scolaire",
    "Class": "Classe",
    "Department": "Département",
    "Subject": "Matière",
    "Teacher": "Enseignant",
    "Student": "Élève",
    "Phone": "Téléphone",
    "Address": "Adresse",
    "Fees": "Frais scolaires",
    "Collected": "Collecté",
    "Outstanding": "Impayé",
    "Amount": "Montant",
    "Payment": "Paiement",
    "Settings": "Paramètres",
    "School System": "Système scolaire",
    "Francophone": "Francophone",
    "Anglophone": "Anglophone",
    "English": "Anglais",
    "French": "Français",
    "School settings saved": "Paramètres scolaires enregistrés",
    "Failed to fetch data": "Échec du chargement des données",
    "Failed to load": "Échec du chargement",
    "Save changes": "Enregistrer les modifications",
    "No students found": "Aucun élève trouvé",
    "No teachers found": "Aucun enseignant trouvé",
    "No classes found": "Aucune classe trouvée",
    "No subjects found": "Aucune matière trouvée",
    "Filter": "Filtrer",
    "All": "Tout",
    "Today": "Aujourd’hui",
    "Month": "Mois",
    "Year": "Année",
    "Attendance": "Présence",
    "Report": "Rapport",
    "Export": "Exporter",
    "Download": "Télécharger",
    "Print": "Imprimer",
    "Back": "Retour",
    "Next": "Suivant",
    "Previous": "Précédent",
    "Continue": "Continuer",
    "Confirm": "Confirmer",
    "Yes": "Oui",
    "No": "Non",
    "Configure the school calendar, teacher pay, and user access.": "Configurez le calendrier scolaire, la rémunération des enseignants et les accès utilisateurs.",
    "School Schedule & Pay Mode": "Calendrier scolaire et mode de rémunération",
    "Settings apply to the selected academic year.": "Les paramètres s’appliquent à l’année scolaire sélectionnée.",
    "Per period": "Par période",
    "Monthly": "Mensuel",
    "Hourly": "Horaire",
    "Users": "Utilisateurs",
    "School": "École",
    "Start Time": "Heure de début",
    "End Time": "Heure de fin",
    "Break Start": "Début de la pause",
    "Break End": "Fin de la pause",
    "Period Duration": "Durée d’une période",
    "Periods Per Day": "Périodes par jour",
    "School Days": "Jours de classe",
    "Teacher Payment Mode": "Mode de rémunération des enseignants",
    "Class period rates saved": "Tarifs horaires des classes enregistrés",
    "Monthly teacher amounts saved": "Salaires mensuels des enseignants enregistrés",
    "Enter a positive monthly amount for every teacher": "Saisissez un montant mensuel positif pour chaque enseignant",
    "Could not save school settings": "Impossible d’enregistrer les paramètres scolaires",
    "Could not load school settings": "Impossible de charger les paramètres scolaires",
    "Failed to load school settings": "Échec du chargement des paramètres scolaires",
    "Add Student": "Ajouter un élève",
    "Add Teacher": "Ajouter un enseignant",
    "Student Information": "Informations sur l’élève",
    "Parent Information": "Informations sur le parent",
    "Contact Information": "Coordonnées",
    "Personal Information": "Informations personnelles",
    "Student Details": "Détails de l’élève",
    "Teacher Details": "Détails de l’enseignant",
    "Admission Number": "Matricule",
    "Matricule": "Matricule",
    "Date of Birth": "Date de naissance",
    "Parent Name": "Nom du parent",
    "Parent Phone": "Téléphone du parent",
    "Registration Date": "Date d’inscription",
    "Enrollment Year": "Année d’inscription",
    "Tuition Fee": "Frais de scolarité",
    "Registration Fee": "Frais d’inscription",
    "Fees Paid": "Frais payés",
    "Fees Due": "Frais restants",
    "Qualification": "Diplôme",
    "Monthly Salary": "Salaire mensuel",
    "Assigned Classes": "Classes attribuées",
    "No subjects assigned": "Aucune matière attribuée",
    "No classes assigned": "Aucune classe attribuée",
    "No classes assigned to you": "Aucune classe ne vous est attribuée",
    "Ask an admin to assign you to subjects and classes.": "Demandez à un administrateur de vous attribuer des matières et des classes.",
    "No students in this class.": "Aucun élève dans cette classe.",
    "No teachers found.": "Aucun enseignant trouvé.",
    "No timetable data available": "Aucune donnée d’emploi du temps disponible",
    "Loading your timetable...": "Chargement de votre emploi du temps...",
    "Loading timetable...": "Chargement de l’emploi du temps...",
    "Download My Timetable": "Télécharger mon emploi du temps",
    "Mark Attendance": "Faire l’appel",
    "All Teachers": "Tous les enseignants",
    "All Classes": "Toutes les classes",
    "All Departments": "Tous les départements",
    "All Cycles": "Tous les cycles",
    "All Years": "Toutes les années",
    "Selected term": "Trimestre sélectionné",
    "Generate class marksheet": "Générer la liste de notes de la classe",
    "Academic records": "Dossiers scolaires",
    "Summary": "Résumé",
    "Total Outstanding": "Total impayé",
    "Average Due": "Montant moyen restant",
    "Student Name": "Nom de l’élève",
    "Parent": "Parent",
    "Check In": "Heure d’arrivée",
    "Check Out": "Heure de départ",
    "Class Statistics Report": "Rapport des statistiques de classe",
    "Passed": "Admis",
    "Failed": "Échec",
    "Class Average": "Moyenne de la classe",
    "Top 3 Students": "Les 3 meilleurs élèves",
    "Promote": "Faire passer en classe supérieure",
    "No students with outstanding fees": "Aucun élève n’a de frais impayés",
    "Please allow popups for printing": "Veuillez autoriser les fenêtres contextuelles pour imprimer",
    "PDF exported successfully": "PDF exporté avec succès",
    "Search students...": "Rechercher des élèves...",
    "Search teachers...": "Rechercher des enseignants...",
    "Search classes...": "Rechercher des classes...",
    "No results found": "Aucun résultat trouvé",
    "Showing": "Affichage de",
    "of": "sur",
    "entries": "résultats",
    "Page": "Page",
    "First": "Première",
    "Second": "Deuxième",
    "Third": "Troisième",
    "Sequence": "Séquence",
    "Sequence 1": "Séquence 1",
    "Sequence 2": "Séquence 2",
    "Sequence 3": "Séquence 3",
    "Sequence 4": "Séquence 4",
    "Sequence 5": "Séquence 5",
    "Sequence 6": "Séquence 6",
    "Annual": "Annuel",
    "Total": "Total",
    "Rate": "Taux",
    "Average score / 20": "Moyenne / 20",
    "No data": "Aucune donnée",
    "No attendance records found": "Aucun relevé de présence trouvé",
    "Attendance saved successfully": "Présence enregistrée avec succès",
    "Attendance recorded successfully": "Présence enregistrée avec succès",
    "Attendance updated successfully": "Présence mise à jour avec succès",
    "Teacher added successfully": "Enseignant ajouté avec succès",
    "Student added successfully": "Élève ajouté avec succès",
    "User deleted successfully": "Utilisateur supprimé avec succès",
    "Are you sure you want to delete this record?": "Voulez-vous vraiment supprimer cet enregistrement ?",
    "Are you sure you want to delete": "Voulez-vous vraiment supprimer",
    "Processing...": "Traitement...",
    "Saving...": "Enregistrement...",
    "Updating...": "Mise à jour...",
    "Required": "Obligatoire",
    "Optional": "Facultatif",
    "Select all": "Tout sélectionner",
    "Clear all": "Tout effacer",
    "No records found": "Aucun enregistrement trouvé",
    "No data to display": "Aucune donnée à afficher",
    "Welcome to BCHS DOUALA!": "Bienvenue à BCHS DOUALA !",
    "Academic Management System": "Système de gestion scolaire",
    "Starting BCHS DOUALA...": "Démarrage de BCHS DOUALA...",
    "Loading modules...": "Chargement des modules...",
    "Connecting to services...": "Connexion aux services...",
    "Initializing components...": "Initialisation des composants...",
    "Building user interface...": "Préparation de l’interface...",
    "Loading your data...": "Chargement de vos données...",
    "Preparing dashboard...": "Préparation du tableau de bord...",
    "Almost there...": "Presque terminé...",
    "Finalizing setup...": "Finalisation de la configuration...",
    "Ready to launch!": "Prêt à démarrer !",
    "Error loading application": "Erreur lors du chargement de l’application",
    "Preparing your workspace...": "Préparation de votre espace de travail...",
    "Finalizing...": "Finalisation...",
    "Student List": "Liste des élèves",
    "Student Management": "Gestion des élèves",
    "Add New Student": "Ajouter un nouvel élève",
    "Edit Student": "Modifier l’élève",
    "Delete Student": "Supprimer l’élève",
    "View Details": "Voir les détails",
    "Search by name or matricule": "Rechercher par nom ou matricule",
    "Filter by Class": "Filtrer par classe",
    "Outstanding Fees": "Frais impayés",
    "Parent/Guardian": "Parent ou tuteur",
    "Save Student": "Enregistrer l’élève",
    "Update Student": "Mettre à jour l’élève",
    "Teacher List": "Liste des enseignants",
    "Teacher Management": "Gestion des enseignants",
    "Add New Teacher": "Ajouter un nouvel enseignant",
    "Edit Teacher": "Modifier l’enseignant",
    "Delete Teacher": "Supprimer l’enseignant",
    "Save Teacher": "Enregistrer l’enseignant",
    "Update Teacher": "Mettre à jour l’enseignant",
    "Class List": "Liste des classes",
    "Class Management": "Gestion des classes",
    "Add Class": "Ajouter une classe",
    "Edit Class": "Modifier la classe",
    "Delete Class": "Supprimer la classe",
    "Add Subject": "Ajouter une matière",
    "Edit Subject": "Modifier la matière",
    "Delete Subject": "Supprimer la matière",
    "First Cycle": "Premier cycle",
    "Second Cycle": "Second cycle",
    "Select term": "Sélectionner un trimestre",
    "Select year": "Sélectionner une année",
    "Select subject": "Sélectionner une matière",
    "Select teacher": "Sélectionner un enseignant",
    "Select student": "Sélectionner un élève",
    "Student Attendance Register": "Registre de présence des élèves",
    "Attendance Summary": "Résumé des présences",
    "Class Attendance": "Présence de la classe",
    "Daily Attendance": "Présence quotidienne",
    "Mark All Present": "Marquer tous présents",
    "Save Attendance": "Enregistrer les présences",
    "Attendance Rate": "Taux de présence",
    "Attendance Records": "Registres de présence",
    "No attendance data": "Aucune donnée de présence",
    "No attendance records": "Aucun registre de présence",
    "Date Range": "Période",
    "Start Date": "Date de début",
    "End Date": "Date de fin",
    "Period": "Période",
    "Enter Marks": "Saisir les notes",
    "Save Marks": "Enregistrer les notes",
    "No marks found": "Aucune note trouvée",
    "Report Card": "Bulletin scolaire",
    "Photo": "Photo",
    "Student photo": "Photo de l’élève",
    "Take photo": "Prendre la photo",
    "Use webcam": "Utiliser la webcam",
    "Stop camera": "Arrêter la caméra",
    "Upload photo": "Importer une photo",
    "Remove photo": "Supprimer la photo",
    "Student photo preview": "Aperçu de la photo de l’élève",
    "No photo selected": "Aucune photo sélectionnée",
    "Capture with webcam or upload an image": "Prenez une photo avec la webcam ou importez une image",
    "Images are resized before saving. Maximum upload size: 10 MB.": "Les images sont redimensionnées avant l’enregistrement. Taille maximale : 10 Mo.",
    "You can skip this step and add a photo later.": "Vous pouvez ignorer cette étape et ajouter une photo plus tard.",
    "Skip photo": "Ignorer la photo",
    "Camera access is unavailable. Use HTTPS or localhost, or upload a photo instead.": "L’accès à la caméra est indisponible. Utilisez HTTPS ou localhost, ou importez une photo.",
    "Camera permission was denied or no camera was found. You can upload a photo instead.": "L’accès à la caméra a été refusé ou aucune caméra n’a été détectée. Vous pouvez importer une photo.",
    "The camera is still starting. Try again in a moment.": "La caméra démarre. Réessayez dans un instant.",
    "Could not capture the photo. Please try again or upload an image.": "Impossible de prendre la photo. Réessayez ou importez une image.",
    "Choose an image file": "Choisissez un fichier image",
    "Choose an image smaller than 10 MB": "Choisissez une image de moins de 10 Mo",
    "Could not load this image. Try another photo.": "Impossible de charger cette image. Essayez une autre photo.",
    "Photo added": "Photo ajoutée",
    "Not provided": "Non renseignée",
    "Generate Report Cards": "Générer les bulletins scolaires",
    "Download Report Card": "Télécharger le bulletin",
    "Print Report Card": "Imprimer le bulletin",
    "Fees Management": "Gestion des frais scolaires",
    "Payment History": "Historique des paiements",
    "Record Payment": "Enregistrer un paiement",
    "Pay Now": "Payer maintenant",
    "Total Fees": "Total des frais scolaires",
    "Balance": "Solde",
    "Paid": "Payé",
    "Unpaid": "Non payé",
    "Partially Paid": "Partiellement payé",
    "Timetable Management": "Gestion des emplois du temps",
    "Generate Timetable": "Générer l’emploi du temps",
    "Download Timetable": "Télécharger l’emploi du temps",
    "No timetable found": "Aucun emploi du temps trouvé",
    "Monday": "Lundi",
    "Tuesday": "Mardi",
    "Wednesday": "Mercredi",
    "Thursday": "Jeudi",
    "Friday": "Vendredi",
    "Saturday": "Samedi",
    "Sunday": "Dimanche",
    "Dashboard Overview": "Vue d’ensemble du tableau de bord",
    "Welcome": "Bienvenue",
    "Welcome back!": "Bon retour !",
    "Get Started": "Commencer",
    "Login": "Connexion",
    "Log in": "Se connecter",
    "Username": "Nom d’utilisateur",
    "Password": "Mot de passe",
    "Forgot password?": "Mot de passe oublié ?",
    "Remember me": "Se souvenir de moi",
    "Sign in": "Se connecter",
    "Create account": "Créer un compte",
    "All rights reserved.": "Tous droits réservés.",
    "Loading data...": "Chargement des données...",
    "An error occurred": "Une erreur est survenue",
    "Something went wrong": "Une erreur s’est produite",
    "Please try again": "Veuillez réessayer",
    "Changes saved successfully": "Modifications enregistrées avec succès",
    "Record created successfully": "Enregistrement créé avec succès",
    "Record updated successfully": "Enregistrement mis à jour avec succès",
    "Record deleted successfully": "Enregistrement supprimé avec succès",
};

const englishTranslations: Record<string, string> = {
    "Tableau de bord": "Dashboard",
    "Vue d’ensemble": "Overview Dashboard",
    "Élèves": "Students",
    "Enseignants": "Teachers",
    "Classes et matières": "Classes & Subjects",
    "Saisie des notes": "Mark Entry",
    "Présence des élèves": "Student Attendance",
    "Présence des enseignants": "Teacher Attendance",
    "Bulletins scolaires": "Report Cards",
    "Listes de classe": "Class Lists",
    "Frais et finances": "Fees & Finance",
    "Salaires des enseignants": "Teacher Salaries",
    "Paramètres de l’école": "School Settings",
    "Portail scolaire": "School Portal",
    "PORTAIL SCOLAIRE": "SCHOOL PORTAL",
    "Déconnexion": "Sign out",
    "En direct": "Live",
    "Bon retour": "Welcome back",
    "Frais collectés": "Fees Collected",
    "Taux de réussite": "Pass Rate",
    "Moyenne": "Average",
    "Moyennes des classes": "Class Averages",
    "Moyennes des matières": "Subject Averages",
    "Tableau d’excellence": "Excellence Board",
    "Meilleurs élèves": "Top performing students",
    "Évolution des résultats par séquence": "Sequence Performance Trend",
    "Analyse par IA": "AI Insight",
    "Aucune donnée disponible": "No data available",
    "Aucune donnée de classe disponible": "No class data available",
    "Aucune donnée de matière disponible": "No subject data available",
    "Aucune donnée de séquence disponible": "No sequence data available",
    "Réessayer": "Retry",
    "Meilleur": "Best",
    "Basé sur": "Based on",
    "élèves": "students",
    "classes": "classes",
    "affichées": "shown",
    "Matières": "Subjects",
    "Rechercher": "Search",
    "Ajouter": "Add",
    "Modifier": "Edit",
    "Supprimer": "Delete",
    "Enregistrer": "Save",
    "Annuler": "Cancel",
    "Fermer": "Close",
    "Valider": "Submit",
    "Chargement...": "Loading...",
    "Sélectionner": "Select",
    "Sélectionner une classe": "Select a class",
    "Nom": "Name",
    "Nom complet": "Full Name",
    "Sexe": "Gender",
    "Masculin": "Male",
    "Féminin": "Female",
    "Date": "Date",
    "Statut": "Status",
    "Présent": "Present",
    "Absent": "Absent",
    "En retard": "Late",
    "Excusé": "Excused",
    "Trimestre": "Term",
    "Premier trimestre": "First Term",
    "Deuxième trimestre": "Second Term",
    "Troisième trimestre": "Third Term",
    "Année scolaire": "Academic Year",
    "Classe": "Class",
    "Département": "Department",
    "Matière": "Subject",
    "Enseignant": "Teacher",
    "Élève": "Student",
    "Téléphone": "Phone",
    "Adresse": "Address",
    "Frais scolaires": "Fees",
    "Collecté": "Collected",
    "Impayé": "Outstanding",
    "Montant": "Amount",
    "Paiement": "Payment",
    "Paramètres": "Settings",
    "Système scolaire": "School System",
    "Français": "French",
    "Anglais": "English",
    "Paramètres scolaires enregistrés": "School settings saved",
    "Aucun élève trouvé": "No students found",
    "Aucun enseignant trouvé": "No teachers found",
    "Aucune classe trouvée": "No classes found",
    "Aucune matière trouvée": "No subjects found",
    "Filtrer": "Filter",
    "Tout": "All",
    "Aujourd’hui": "Today",
    "Mois": "Month",
    "Année": "Year",
    "Présence": "Attendance",
    "Rapport": "Report",
    "Exporter": "Export",
    "Télécharger": "Download",
    "Imprimer": "Print",
    "Retour": "Back",
    "Suivant": "Next",
    "Précédent": "Previous",
    "Continuer": "Continue",
    "Confirmer": "Confirm",
    "Oui": "Yes",
    "Non": "No",
    "Calendrier scolaire et mode de rémunération": "School Schedule & Pay Mode",
    "Emploi du temps": "Timetable",
    "Emploi du temps des enseignants": "Teacher Timetable",
    "Par période": "Per period",
    "Mensuel": "Monthly",
    "Horaire": "Hourly",
    "Utilisateurs": "Users",
    "École": "School",
    "Heure de début": "Start Time",
    "Heure de fin": "End Time",
    "Début de la pause": "Break Start",
    "Fin de la pause": "Break End",
    "Durée d’une période": "Period Duration",
    "Périodes par jour": "Periods Per Day",
    "Jours de classe": "School Days",
    "Mode de rémunération des enseignants": "Teacher Payment Mode",
    "Tarifs horaires des classes enregistrés": "Class period rates saved",
    "Salaires mensuels des enseignants enregistrés": "Monthly teacher amounts saved",
    "Saisissez un montant mensuel positif pour chaque enseignant": "Enter a positive monthly amount for every teacher",
    "Ajouter un élève": "Add Student",
    "Ajouter un enseignant": "Add Teacher",
    "Informations sur l’élève": "Student Information",
    "Informations sur le parent": "Parent Information",
    "Coordonnées": "Contact Information",
    "Informations personnelles": "Personal Information",
    "Détails de l’élève": "Student Details",
    "Détails de l’enseignant": "Teacher Details",
    "Matricule": "Matricule",
    "Date de naissance": "Date of Birth",
    "Nom du parent": "Parent Name",
    "Téléphone du parent": "Parent Phone",
    "Date d’inscription": "Registration Date",
    "Année d’inscription": "Enrollment Year",
    "Frais de scolarité": "Tuition Fee",
    "Frais d’inscription": "Registration Fee",
    "Frais payés": "Fees Paid",
    "Frais restants": "Fees Due",
    "Diplôme": "Qualification",
    "Salaire mensuel": "Monthly Salary",
    "Classes attribuées": "Assigned Classes",
    "Aucune matière attribuée": "No subjects assigned",
    "Aucune classe attribuée": "No classes assigned",
    "Aucune classe ne vous est attribuée": "No classes assigned to you",
    "Demandez à un administrateur de vous attribuer des matières et des classes.": "Ask an admin to assign you to subjects and classes.",
    "Aucun élève dans cette classe.": "No students in this class.",
    "Faire l’appel": "Mark Attendance",
    "Tous les enseignants": "All Teachers",
    "Toutes les classes": "All Classes",
    "Tous les départements": "All Departments",
    "Tous les cycles": "All Cycles",
    "Toutes les années": "All Years",
    "Trimestre sélectionné": "Selected term",
    "Générer la liste de notes de la classe": "Generate class marksheet",
    "Dossiers scolaires": "Academic records",
    "Résumé": "Summary",
    "Total impayé": "Total Outstanding",
    "Montant moyen restant": "Average Due",
    "Nom de l’élève": "Student Name",
    "Heure d’arrivée": "Check In",
    "Heure de départ": "Check Out",
    "Rapport des statistiques de classe": "Class Statistics Report",
    "Admis": "Passed",
    "Échec": "Failed",
    "Moyenne de la classe": "Class Average",
    "Les 3 meilleurs élèves": "Top 3 Students",
    "Faire passer en classe supérieure": "Promote",
    "Veuillez autoriser les fenêtres contextuelles pour imprimer": "Please allow popups for printing",
    "Rechercher des élèves...": "Search students...",
    "Rechercher des enseignants...": "Search teachers...",
    "Rechercher des classes...": "Search classes...",
    "Aucun résultat trouvé": "No results found",
    "Affichage de": "Showing",
    "résultats": "entries",
    "Première": "First",
    "Deuxième": "Second",
    "Troisième": "Third",
    "Séquence": "Sequence",
    "Annuel": "Annual",
    "Taux": "Rate",
    "Aucune donnée": "No data",
    "Aucun relevé de présence trouvé": "No attendance records found",
    "Présence enregistrée avec succès": "Attendance saved successfully",
    "Présence mise à jour avec succès": "Attendance updated successfully",
    "Enseignant ajouté avec succès": "Teacher added successfully",
    "Élève ajouté avec succès": "Student added successfully",
    "Utilisateur supprimé avec succès": "User deleted successfully",
    "Traitement...": "Processing...",
    "Enregistrement...": "Saving...",
    "Mise à jour...": "Updating...",
    "Obligatoire": "Required",
    "Facultatif": "Optional",
    "Tout sélectionner": "Select all",
    "Tout effacer": "Clear all",
    "Aucun enregistrement trouvé": "No records found",
    "Aucune donnée à afficher": "No data to display",
    "Bienvenue à BCHS DOUALA !": "Welcome to BCHS DOUALA!",
    "Système de gestion scolaire": "Academic Management System",
    "Démarrage de BCHS DOUALA...": "Starting BCHS DOUALA...",
    "Chargement des modules...": "Loading modules...",
    "Connexion aux services...": "Connecting to services...",
    "Initialisation des composants...": "Initializing components...",
    "Préparation de l’interface...": "Building user interface...",
    "Chargement de vos données...": "Loading your data...",
    "Préparation du tableau de bord...": "Preparing dashboard...",
    "Presque terminé...": "Almost there...",
    "Finalisation de la configuration...": "Finalizing setup...",
    "Prêt à démarrer !": "Ready to launch!",
    "Erreur lors du chargement de l’application": "Error loading application",
    "Préparation de votre espace de travail...": "Preparing your workspace...",
    "Finalisation...": "Finalizing...",
    "Liste des élèves": "Student List",
    "Gestion des élèves": "Student Management",
    "Ajouter un nouvel élève": "Add New Student",
    "Modifier l’élève": "Edit Student",
    "Supprimer l’élève": "Delete Student",
    "Voir les détails": "View Details",
    "Rechercher par nom ou matricule": "Search by name or matricule",
    "Filtrer par classe": "Filter by Class",
    "Frais impayés": "Outstanding Fees",
    "Parent ou tuteur": "Parent/Guardian",
    "Enregistrer l’élève": "Save Student",
    "Mettre à jour l’élève": "Update Student",
    "Liste des enseignants": "Teacher List",
    "Gestion des enseignants": "Teacher Management",
    "Ajouter un nouvel enseignant": "Add New Teacher",
    "Modifier l’enseignant": "Edit Teacher",
    "Supprimer l’enseignant": "Delete Teacher",
    "Enregistrer l’enseignant": "Save Teacher",
    "Mettre à jour l’enseignant": "Update Teacher",
    "Liste des classes": "Class List",
    "Gestion des classes": "Class Management",
    "Ajouter une classe": "Add Class",
    "Modifier la classe": "Edit Class",
    "Supprimer la classe": "Delete Class",
    "Ajouter une matière": "Add Subject",
    "Modifier une matière": "Edit Subject",
    "Supprimer une matière": "Delete Subject",
    "Premier cycle": "First Cycle",
    "Second cycle": "Second Cycle",
    "Sélectionner un trimestre": "Select term",
    "Sélectionner une année": "Select year",
    "Sélectionner une matière": "Select subject",
    "Sélectionner un enseignant": "Select teacher",
    "Sélectionner un élève": "Select student",
    "Registre de présence des élèves": "Student Attendance Register",
    "Résumé des présences": "Attendance Summary",
    "Présence de la classe": "Class Attendance",
    "Présence quotidienne": "Daily Attendance",
    "Marquer tous présents": "Mark All Present",
    "Enregistrer les présences": "Save Attendance",
    "Taux de présence": "Attendance Rate",
    "Registres de présence": "Attendance Records",
    "Aucune donnée de présence": "No attendance data",
    "Aucun registre de présence": "No attendance records",
    "Date de début": "Start Date",
    "Date de fin": "End Date",
    "Saisir les notes": "Enter Marks",
    "Enregistrer les notes": "Save Marks",
    "Aucune note trouvée": "No marks found",
    "Bulletin scolaire": "Report Card",
    "Photo de l’élève": "Student photo",
    "Prendre la photo": "Take photo",
    "Utiliser la webcam": "Use webcam",
    "Arrêter la caméra": "Stop camera",
    "Importer une photo": "Upload photo",
    "Supprimer la photo": "Remove photo",
    "Aperçu de la photo de l’élève": "Student photo preview",
    "Aucune photo sélectionnée": "No photo selected",
    "Prenez une photo avec la webcam ou importez une image": "Capture with webcam or upload an image",
    "Les images sont redimensionnées avant l’enregistrement. Taille maximale : 10 Mo.": "Images are resized before saving. Maximum upload size: 10 MB.",
    "Vous pouvez ignorer cette étape et ajouter une photo plus tard.": "You can skip this step and add a photo later.",
    "Ignorer la photo": "Skip photo",
    "L’accès à la caméra est indisponible. Utilisez HTTPS ou localhost, ou importez une photo.": "Camera access is unavailable. Use HTTPS or localhost, or upload a photo instead.",
    "L’accès à la caméra a été refusé ou aucune caméra n’a été détectée. Vous pouvez importer une photo.": "Camera permission was denied or no camera was found. You can upload a photo instead.",
    "La caméra démarre. Réessayez dans un instant.": "The camera is still starting. Try again in a moment.",
    "Impossible de prendre la photo. Réessayez ou importez une image.": "Could not capture the photo. Please try again or upload an image.",
    "Choisissez un fichier image": "Choose an image file",
    "Choisissez une image de moins de 10 Mo": "Choose an image smaller than 10 MB",
    "Impossible de charger cette image. Essayez une autre photo.": "Could not load this image. Try another photo.",
    "Photo ajoutée": "Photo added",
    "Non renseignée": "Not provided",
    "Générer les bulletins scolaires": "Generate Report Cards",
    "Télécharger le bulletin": "Download Report Card",
    "Imprimer le bulletin": "Print Report Card",
    "Gestion des frais scolaires": "Fees Management",
    "Historique des paiements": "Payment History",
    "Enregistrer un paiement": "Record Payment",
    "Payer maintenant": "Pay Now",
    "Total des frais scolaires": "Total Fees",
    "Solde": "Balance",
    "Payé": "Paid",
    "Non payé": "Unpaid",
    "Partiellement payé": "Partially Paid",
    "Gestion des emplois du temps": "Timetable Management",
    "Générer l’emploi du temps": "Generate Timetable",
    "Télécharger l’emploi du temps": "Download Timetable",
    "Aucun emploi du temps trouvé": "No timetable found",
    "Lundi": "Monday",
    "Mardi": "Tuesday",
    "Mercredi": "Wednesday",
    "Jeudi": "Thursday",
    "Vendredi": "Friday",
    "Samedi": "Saturday",
    "Dimanche": "Sunday",
    "Vue d’ensemble du tableau de bord": "Dashboard Overview",
    "Bienvenue": "Welcome",
    "Bon retour !": "Welcome back!",
    "Commencer": "Get Started",
    "Connexion": "Login",
    "Se connecter": "Sign in",
    "Nom d’utilisateur": "Username",
    "Mot de passe": "Password",
    "Mot de passe oublié ?": "Forgot password?",
    "Se souvenir de moi": "Remember me",
    "Créer un compte": "Create account",
    "Tous droits réservés.": "All rights reserved.",
    "Chargement des données...": "Loading data...",
    "Une erreur est survenue": "An error occurred",
    "Une erreur s’est produite": "Something went wrong",
    "Veuillez réessayer": "Please try again",
    "Modifications enregistrées avec succès": "Changes saved successfully",
    "Enregistrement créé avec succès": "Record created successfully",
    "Enregistrement mis à jour avec succès": "Record updated successfully",
    "Enregistrement supprimé avec succès": "Record deleted successfully",
};

const dictionary: Record<Language, Record<string, string>> = {
    en: {
        ...Object.fromEntries(Object.entries(frenchTranslations).map(([english, french]) => [french, english])),
        ...englishTranslations,
    },
    fr: frenchTranslations,
};

export function languageForSection(section: SchoolSection): Language {
    return section === "francophone" ? "fr" : "en";
}

export function translateText(value: string, language: Language): string {
    const translations = dictionary[language];
    const exact = translations[value.trim()];
    if (exact) return value.replace(value.trim(), exact);

    const keys = Object.keys(translations).sort((a, b) => b.length - a.length);
    return keys.reduce((text, key) => {
        if (key.length < 4) return text;
        return text.replace(new RegExp(`(^|\\b)${escapeRegExp(key)}(?=\\b|$)`, "gi"), (match, prefix: string) => `${prefix}${translations[key]}`);
    }, value);
}

export function translateTextForCurrentSection(value: string): string {
    return translateText(value, languageForSection(getStoredSchoolSection()));
}

function escapeRegExp(value: string) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

type LanguageContextValue = {
    section: SchoolSection;
    language: Language;
    isFrench: boolean;
    t: (value: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [section, setSection] = useState<SchoolSection>(getStoredSchoolSection);
    const language = languageForSection(section);

    useEffect(() => {
        const refreshSection = () => setSection(getStoredSchoolSection());
        window.addEventListener("school-section-change", refreshSection);
        window.addEventListener("storage", refreshSection);
        return () => {
            window.removeEventListener("school-section-change", refreshSection);
            window.removeEventListener("storage", refreshSection);
        };
    }, []);

    useEffect(() => {
        document.documentElement.lang = language;
    }, [language]);

    const value = useMemo<LanguageContextValue>(() => ({
        section,
        language,
        isFrench: language === "fr",
        t: (text) => translateText(text, language),
    }), [section, language]);

    return createElement(LanguageContext.Provider, { value }, children);
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within LanguageProvider");
    return context;
}
